spring:
  application:
    name: billing-application
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/billing}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        transaction:
          coordinator_class: jdbc
    open-in-view: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    com.example.billing: DEBUG
    org.springframework.web: DEBUG


